sudo: false
language: node_js
node_js:
- '10'
script: bash ./deploy.sh
branches:
  only:
  - master
env:
  global:
  - GH_REF: github.com/openactive/ns-beta.git
  - secure: 05maD2hZTl9lvZJawP9rfgfl6B1sxPi4XgjU4xai99ddv4YQmUfYahftsO9D93vwcxCS6m+MhfjekX3KcujGsX/lm6EUiq2j822XyeLR527mQmIESX7pz5XR4mEUyo89ilUkk1bWYdKcLTTy988B+br/Dok7Zx0cXwBJtKujif+Ar466P/rT5CtjCySMmQQojk/ZD5N3SrT1lgaaWt2Ul2Zw2OTJA306RQCsbvrOazUU989EwAMIjVr9TMR1gfaPmaPEV8L2YTMVvSpcNUmCnM0Wd4NIqFfV+/2FE6d1JBpW0+CjEqOGpREay9KAQQgO1iQi/6fzWNQdJ7LHlvscx1H69KgkVzqsJT6ZD5TjS7tiVOyxHnOv2IIf39pM7GUZb9iOBzK8HDmohXDcPh8iK+pZVZndTLHo/98cJI6TgHGl+TGd0//b6PEwOZIFBanBLZP/g1a+XpvTaF940jPAjVqFu53AzIZvInpRqfmgkVYi+joh4UgYdsBDZPc6n53hLf7k1CEhGRgOhAjpvOL+62AEhIaSEZ6lSKbl6uvCfFQy52TcQxpwyMMuqosLnAZcooBeRwmSqR2NrYYqmXX7702Rkb1QEpDIVEqq+PvnP1cv5oOXtg443PAS857NYAl5OXLh5kNa1KBMwoeKpV5VwWDlQUPhFPaBVwck+4EM5dQ=
